name: "Federal Register"
description: "Access the Daily Journal of the United States Government"
inputs:
  agency:
    description: |
      Agencies, see: 
      curl -X GET "https://www.federalregister.gov/api/v1/agencies" -H "accept: */*"

  document_number:
    description: |
      Documents, see: 
      curl -X GET "https://www.federalregister.gov/api/v1/documents/2022-08590.json" -H "accept: */*"

outputs:
  json:
    description: "The output in as json."
runs:
  using: "node16"
  main: "dist/index.js"
