name: "Federal Register"
description: "Access the Daily Journal of the United States Government"
inputs:
  read:
    description: |
      The type of content to read.
    required: true
  agency: # id of input
    description: |
      Agencies, see: 
      curl -X GET "https://www.federalregister.gov/api/v1/agencies" -H "accept: */*"
    required: true

outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "node16"
  main: "dist/index.js"
