on: [push]

jobs:
  read_docs:
    runs-on: ubuntu-latest
    name: Latest Docs from Commerce Department
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Read latest docs
        uses: ./ # Uses an action in the root directory
        id: read
        with:
          read: "recent-documents"
          agency: "commerce-department"

      - name: Review the results
        run: |
          echo '${{ steps.read.outputs.json }}' | jq -r '.description'
