on: [push]

jobs:
  checkout:
    runs-on: ubuntu-latest
    name: Checkout
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Save
        uses: actions/cache@v3
        with:
          path: |
            ./*
          key: ${{ github.sha }}

  read_docs:
    needs:
      - checkout
    runs-on: ubuntu-latest
    name: Read Documents
    outputs:
      json: ${{ steps.read.outputs.json }}
    steps:
      - name: Cache Restore
        uses: actions/cache@v2
        id: cache-restore
        with:
          path: |
            ./*
          key: ${{ github.sha }}
      - name: Read Documents from Commerce Department
        uses: ./
        id: read
        with:
          agency: "commerce-department"

      - name: Review the results
        run: |-
          echo '${{ fromJson(steps.read.outputs.json).description }}'

  read_text:
    needs:
      - read_docs
    runs-on: ubuntu-latest
    name: Read Document
    steps:
      - name: Cache Restore
        uses: actions/cache@v2
        id: cache-restore
        with:
          path: |
            ./*
          key: ${{ github.sha }}
      - name: Read a Document
        uses: ./
        id: read
        with:
          document_number: ${{ fromJson(needs.read_docs.outputs.json).results[0].document_number }}
          raw: true

      - name: Review the results
        run: |-
          echo "${{ steps.read.outputs.text }}"
